
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Idris Ya'u  ## put your name
title: 'Enterpreneure; Affliate marketer'  ## your title
location: Kano , Nigeria


## Social Profiles
facebook: http://www.facebook.com/iycosmeticss  ## your facebook account url
twitter: http://www.twitter.com/iiycosmetics  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
